spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devMysql,devRedis
      "product": productMysql,productRedis
      "test": testMysql,testRedis
---
#开发环境
server:
  port: 8080

logging:
  level:
    root: info
    g1 : debug
    g2 : info
  group:
    g1: com.zjyun.springboot.controller,com.zjyun.springboot.service
    g2: com.zjyun.springboot.entity



#Mybatis-Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl