spring:
  profiles:
    active: dev
---
#开发环境
server:
  port: 8080

logging:
  level:
    root: info

#Mybatis-Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
