/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package example.avro;  
@SuppressWarnings("all")
/** 颜色枚举类 */
@org.apache.avro.specific.AvroGenerated
public enum ColorEnums { 
  red, green, yellow  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ColorEnums\",\"namespace\":\"example.avro\",\"doc\":\"颜色枚举类\",\"symbols\":[\"red\",\"green\",\"yellow\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
